//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SaludPlus.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Consultas
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Consultas()
        {
            this.Recetas = new HashSet<Recetas>();
        }
    
        public int ConsultaID { get; set; }
        public int CitaID { get; set; }
        public int MedicoID { get; set; }
        public int PacienteID { get; set; }
        public System.DateTime FechaConsulta { get; set; }
        public string MotivoConsulta { get; set; }
        public string ExamenFisico { get; set; }
        public string Diagnostico { get; set; }
        public string Tratamiento { get; set; }
        public string Indicaciones { get; set; }
        public Nullable<decimal> PesoKg { get; set; }
        public Nullable<decimal> TallaCm { get; set; }
        public string PresionArterial { get; set; }
        public Nullable<decimal> Temperatura { get; set; }
        public Nullable<System.DateTime> ProximaRevision { get; set; }
    
        public virtual Citas Citas { get; set; }
        public virtual Medicos Medicos { get; set; }
        public virtual Pacientes Pacientes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Recetas> Recetas { get; set; }
    }
}
