//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SaludPlus.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DetalleReceta
    {
        public int DetalleID { get; set; }
        public int RecetaID { get; set; }
        public int MedicamentoID { get; set; }
        public string Dosis { get; set; }
        public int Cantidad { get; set; }
        public string Indicaciones { get; set; }
        public bool Estado { get; set; }
    
        public virtual Medicamentos Medicamentos { get; set; }
        public virtual Recetas Recetas { get; set; }
    }
}
