//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SaludPlus.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Medicamentos
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Medicamentos()
        {
            this.DetalleReceta = new HashSet<DetalleReceta>();
        }
    
        public int MedicamentoID { get; set; }
        public string Nombre { get; set; }
        public string Laboratorio { get; set; }
        public string Presentacion { get; set; }
        public string ViaAdministracion { get; set; }
        public int StockActual { get; set; }
        public int StockMinimo { get; set; }
        public Nullable<decimal> Precio { get; set; }
        public bool Activo { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DetalleReceta> DetalleReceta { get; set; }
    }
}
